In [3]:
%matplotlib inline
from tqdm import tqdm
import numpy as np
import pymc3 as pm
from theano import shared
import theano.tensor as tt
import theano
import pandas as pd
from pymc3.distributions.dist_math import binomln, betaln, bound
np.set_printoptions(suppress=True)

In [4]:
df = pd.read_csv("mturk_surveys.csv")
df["hit_answered_date"]=pd.to_datetime(df["hit_answered_date"])
df['date'] = pd.to_datetime(df['hit_answered_date'].apply(lambda x : x.date()))

# Create a list of all unique worker IDs 
workers = pd.DataFrame(list(set(df.worker_id)), columns=['worker_id']).reset_index().set_index('worker_id')

In [7]:
# Calculate the time period of each survey answer. 
# Below we take out time period to be 30-day periods. 
# We can change this to be weeks, months, or anything else
window_length = 30
minDate = min(df['date'])
df['period'] = (df['date'] - minDate).dt.days // window_length 

In [8]:
df

Unnamed: 0  gender       hit_answered_date        hit_creation_date  \
0                0    male 2018-02-08 19:19:56.215  2018-02-08 18:13:16.000   
1                1    male 2018-02-08 19:14:13.308  2018-02-08 19:13:13.000   
2                2  female 2018-02-08 19:00:46.391  2018-02-08 18:58:15.000   
3                3    male 2018-02-08 18:54:31.768  2018-02-08 17:13:12.000   
4                4    male 2018-02-08 18:45:51.804  2018-02-08 18:43:21.000   
5                5    male 2018-02-08 18:30:43.987  2018-02-08 18:28:18.000   
6                6  female 2018-02-08 17:59:39.302  2018-02-08 17:43:23.000   
7                7    male 2018-02-08 17:59:30.498  2018-02-08 17:58:28.000   
8                8  female 2018-02-08 17:38:32.908  2018-02-08 16:58:10.000   
9                9  female 2018-02-08 17:38:25.625                      NaN   
10              10  female 2018-02-08 17:38:24.728                      NaN   
11              11    male 2018-02-08 17:32:33.605  2018-02-08 17:28:11.000   
12              12    male 2018-02-08 16:46:25.103  2018-02-08 16:43:11.000   
13              13    male 2018-02-08 16:30:28.070  2018-02-08 16:28:09.000   
14              14    male 2018-02-08 16:17:38.300  2018-02-08 15:43:13.000   
15              15  female 2018-02-08 16:16:59.803  2018-02-08 16:13:11.000   
16              16  female 2018-02-08 16:00:18.905  2018-02-08 15:58:12.000   
17              17    male 2018-02-08 15:31:04.701  2018-02-08 15:28:12.000   
18              18    male 2018-02-08 15:30:12.873  2018-02-08 14:28:11.000   
19              19    male 2018-02-08 15:20:14.660  2018-02-08 15:13:12.000   
20              20  female 2018-02-08 15:09:24.605  2018-02-08 14:13:16.000   
21              21    male 2018-02-08 14:59:24.000  2018-02-08 14:58:11.000   
22              22  female 2018-02-08 14:45:36.963  2018-02-08 13:43:14.000   
23              23    male 2018-02-08 14:45:20.830  2018-02-08 14:43:13.000   
24              24    male 2018-02-08 13:59:57.345  2018-02-08 13:58:14.000   
25              25    male 2018-02-08 13:30:52.870  2018-02-08 13:28:11.000   
26              26  female 2018-02-08 13:14:15.605  2018-02-08 12:43:13.000   
27              27  female 2018-02-08 13:14:14.146  2018-02-08 13:13:11.000   
28              28    male 2018-02-08 13:02:22.483  2018-02-08 12:58:12.000   
29              29    male 2018-02-08 12:49:23.447  2018-02-08 11:28:15.000   
...            ...     ...                     ...                      ...   
103328      103328  female 2015-03-26 18:57:05.187  2015-03-26 18:52:44.000   
103329      103329    male 2015-03-26 18:38:43.408  2015-03-26 18:37:36.000   
103330      103330  female 2015-03-26 18:23:12.754  2015-03-26 18:22:27.000   
103331      103331    male 2015-03-26 18:08:10.110  2015-03-26 18:07:19.000   
103332      103332  female 2015-03-26 17:53:06.760  2015-03-26 17:52:11.000   
103333      103333  female 2015-03-26 17:37:35.951  2015-03-26 17:37:02.000   
103334      103334    male 2015-03-26 17:25:57.411  2015-03-26 17:21:54.000   
103335      103335  female 2015-03-26 17:07:44.355  2015-03-26 17:06:45.000   
103336      103336  female 2015-03-26 16:59:53.693  2015-03-26 16:51:37.000   
103337      103337    male 2015-03-26 16:39:19.636  2015-03-26 16:36:28.000   
103338      103338  female 2015-03-26 16:22:53.931  2015-03-26 16:21:22.000   
103339      103339  female 2015-03-26 16:07:55.606  2015-03-26 16:06:16.000   
103340      103340    male 2015-03-26 15:51:33.492  2015-03-26 15:51:08.000   
103341      103341  female 2015-03-26 15:37:16.242  2015-03-26 15:35:59.000   
103342      103342  female 2015-03-26 15:27:18.526  2015-03-26 15:20:51.000   
103343      103343    male 2015-03-26 15:06:44.851  2015-03-26 15:05:43.000   
103344      103344    male 2015-03-26 14:53:03.882  2015-03-26 14:50:35.000   
103345      103345    male 2015-03-26 14:42:47.384  2015-03-26 14:35:27.000   
103346      103346    male 2015-03-26 14:21:06.661  2015-0

In [9]:
data = df.pivot_table(
    index = 'worker_id',
    values = 'period',                    
    aggfunc=('count','min','max')
)

In [25]:
data[data['count'] > (data['max']-data['min'] + 1)]

count  max  min
worker_id                                        
000314db2adbfc1680937b7a9a7b0564      7   17   17
00973b532a389cae01e4821b74e5966b      2   10   10
0189e5358390fe1a746c581fd0bac904      3   23   23
01ded1b837424aa6400085f5e34205ef      2    6    6
01fe1039c33407583bb75ecdd9b2cfd9      3   25   24
0282473e990c8b97d93b932ba920025c      2   10   10
02908ecb265c8c77b2d3c5724d222acb      2   20   20
02e3c42db87d78664987b9967ca4d923      2   11   11
03711f3dd781f444764139ee93824c0d      2    7    7
0499f064272db6563a606cb3ddd6abc6      4    2    2
056df52e3500f2e0c9b382534fca7b26      2    2    2
05aabba1001018136dade4bb0f7bf293      2   20   20
05ac8ad542f4a63ee400b86e0db03f95      2    3    3
060d75d5aa8a90dabf0663bfb1e195e0      2   28   28
065a4a5a168f77cbf69ed156486b947a      2    6    6
06943d2d6e568c3a11ca874de9622b6a      2    9    9
09d882a596fed63d411a7b269233295b      2   23   23
0a89450b47507e8e4076732101de4141      4   33   33
0af8eb8d14bb04ea18b3bd26c448c1e3      2    5    5
0b2960585da7858464319a4eddf31fa4      2   18   18
0b9d898f66fb139641d9769cacf6d39e      6    8    8
0bb0dc76e5c9f1fea2794825b1f87607      3   34   33
0bf48a724fbb6ef9658b66209c0e1040      5   26   26
0bf71fc92acbfe4d0d2adaf588df4916      2   34   34
0d3baf23e4dc33a6d464edb8c21110f4      3   32   31
0d4efdc4aa49bc131503f42e35c3083b      2   31   31
0d5ded3ed3979515f40ba5a7f1b2a5ad      2   12   12
0d7162337689b84a2f8072da0155e0ae      5   30   30
0daaa8d8cae286aa9a6771dcf9f0cf2c      2    3    3
0e13a8f6d459814faa72e61b65bb8d62     24   30    8
...                                 ...  ...  ...
f64c5cae35b2a698384877a96b7baccd      2   22   22
f6a42d26673a89ae55f389263e67245b      2    4    4
f6ba5378c99da3bf210df8d186b6e206      2   20   20
f6ece3ba57706e2268f987e5080c0f38      3   21   21
f6f8e7bc06ab07f5a4e1d2503abe1bc6      2   29   29
f70adb1b99348a69b843633640a724c8      3   18   18
f7c1c93a31e4b1276b80a455b42d9c3a      2   10   10
f7d83eb48b651de654659b81fa7b2c1a      2   21   21
f85392b9fd9cbd612b6574b06c532159      4   31   29
f862402a0809df1ee037df50ebf4fabe      2   18   18
f879af4300811f0d0f8a5da2d5658bf5      8   34   33
f955d1f8d3ee53c41707d64b349663b5      2    4    4
f97d5b1980053c1bc5416dac55c8812b      2   17   17
f9b002f289207f00a2a8139258ecf71e      3   32   31
fae8b18b5eb9a0281fbd5000753c4142      2   25   25
fb16f13bf5eb8b09a0eac484763f68ff      2    1    1
fba41b86d7da2edecabf3fb5a979851f     12   16   13
fbcdba6956ca65d37ecd05c25c7f6cf0      4   30   29
fc14a340ce12855dee2ee7405fb32156      2   27   27
fc2dd74b8aa8ba685d60df7175eee94a      2   28   28
fca992c5fc50f58cb1cbaf30c560b7fc      2   18   18
fcb339218d014b42abc0dc8a71771efb      2   21   21
fd22b796765c2d14ae0f141134e9dc49      3   31   31
fd621df5f28a4ef5878cc45b25477be5      9   23   21
fdaa1638b0ec0b272f6e97801994493b      2   16   16
fdab9a5668ad1f21bae6f2155ea589f2      2    8    8
fdf9e89b2d811684066e95ca5c85861a      2   25   25
fe030066dd003f7e6d71d25b53fe9203      2   19   19
fe446469ae65702eaa1fc46e2bf4ebc2      2   20   20
feb6a5048b5bb4b30306a3afa0f862de      5    3    3

[609 rows x 3 columns]

In [26]:
df[df.worker_id == 'feb6a5048b5bb4b30306a3afa0f862de']

Unnamed: 0 gender       hit_answered_date        hit_creation_date  \
92741       92741   male 2015-07-16 09:18:56.519                      NaN   
92742       92742   male 2015-07-16 09:18:56.443                      NaN   
92743       92743   male 2015-07-16 09:18:56.383                      NaN   
92744       92744   male 2015-07-16 09:18:56.264  2015-07-16 08:38:11.000   
92745       92745   male 2015-07-16 09:18:56.256                      NaN   

        household_income household_size location_city location_country  \
92741  Less than $10,000              3         kochi               IN   
92742  Less than $10,000              3         kochi               IN   
92743  Less than $10,000              3         kochi               IN   
92744  Less than $10,000              3         kochi               IN   
92745  Less than $10,000              3         kochi               IN   

      location_region marital_status  post_to_completion_secs  \
92741              kl         single                      NaN   
92742              kl         single                      NaN   
92743              kl         single                      NaN   
92744              kl         single                   2445.0   
92745              kl         single                      NaN   

                              worker_id  year_of_birth       date  period  
92741  feb6a5048b5bb4b30306a3afa0f862de           1992 2015-07-16       3  
92742  feb6a5048b5bb4b30306a3afa0f862de           1992 2015-07-16       3  
92743  feb6a5048b5bb4b30306a3afa0f862de           1992 2015-07-16       3  
92744  feb6a5048b5bb4b30306a3afa0f862de           1992 2015-07-16       3  
92745  feb6a5048b5bb4b30306a3afa0f862de           1992 2015-07-16       3

In [8]:
df = pd.read_csv("mturk_surveys.csv")
df["hit_answered_date"]=pd.to_datetime(df["hit_answered_date"])
df['date'] = pd.to_datetime(df['hit_answered_date'].apply(lambda x : x.date()))

# Create a list of all unique worker IDs 
workers = pd.DataFrame(list(set(df.worker_id)), columns=['worker_id']).reset_index().set_index('worker_id')
I = len(workers)

CH = np.zeros((I,K))

# Calculate the time period of each survey answer. 
# Below we take out time period to be 30-day periods. 
# We can change this to be weeks, months, or anything else
window_length = 30
minDate = min(df['date'])
df['period'] = (df['date'] - minDate).dt.days // window_length 
K = df['period'].max() + 1

# We give each worker an numerical id
df['idx'] = (df['worker_id']).astype('category').cat.codes

# We generate the full capture history for all workers IxK
seq = df[['idx', 'period']].values
seq = np.r_[seq].T
CH[seq[0], seq[1]] = 1

# We compute the capture history patterns and their frequencies
CH, Nh = np.unique(CH, axis=0, return_counts = True)

array([  31, 1092,  865, ...,    1,    1,    1])

In [39]:
df = pd.read_csv("mturk_surveys.csv")
df["hit_answered_date"]=pd.to_datetime(df["hit_answered_date"])
df['date'] = pd.to_datetime(df['hit_answered_date'].apply(lambda x : x.date()))

# Create a list of all unique worker IDs 
workers = pd.DataFrame(list(set(df.worker_id)), columns=['worker_id']).reset_index().set_index('worker_id')
I = len(workers)

# Calculate the time period of each survey answer. 
# Below we take out time period to be 30-day periods. 
# We can change this to be weeks, months, or anything else
window_length = 30
minDate = min(df['date'])
df['period'] = (df['date'] - minDate).dt.days // window_length 

K = df['period'].max() + 1

data = df.pivot_table(
    index = 'worker_id',
    values = 'period',                    
    aggfunc=('count','min','max')
).join(workers).set_index('index').sort_index()

data.head(10)

count  max  min
index                 
0          2   27   20
1          1    5    5
2          1   28   28
3          4   31    9
4          2   24   17
5          1    4    4
6          7   21    4
7          1   18   18
8          1    5    5
9          1   17   17

In [47]:
data = data.groupby(['count','max', 'min']).size().reset_index(name='count_history')
len(data)

4118

In [18]:
np.unique(data.values.shape, axis = 0)

array([    3, 46145])

In [23]:
np.unique(data.values)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 37])

In [49]:
data.values

array([[ 1,  0,  0,  1],
       [ 1,  1,  1,  1],
       [ 1,  2,  2,  1],
       ...,
       [33, 34,  0,  1],
       [34, 34,  0,  1],
       [37, 34,  0,  1]])

In [27]:
test = np.array([[ 2, 27, 20],
       [ 1, 28, 28],
       [ 1, 28, 28]])

In [50]:
CH, nh = np.unique(data.values, axis = 0, return_counts = True)

In [51]:
len(CH)

4118

In [44]:
data

count  max  min
index                 
0          2   27   20
1          1    5    5
2          1   28   28
3          4   31    9
4          2   24   17
5          1    4    4
6          7   21    4
7          1   18   18
8          1    5    5
9          1   17   17
10         1    3    3
11         1   15   15
12        20   33   13
13         1   12   12
14         3   13    8
15         1   16   16
16         1   14   14
17         1    8    8
18         3   12    6
19         2   12    7
20         1    4    4
21         1   34   34
22         1   21   21
23         1   12   12
24         1   16   16
25         3   19   19
26         1   33   33
27         1   28   28
28         1   15   15
29         1    9    9
...      ...  ...  ...
46115      3   26    2
46116      5   30   16
46117      2    5    0
46118      1    4    4
46119      2    8    0
46120      1   22   22
46121      2   32   30
46122      1    2    2
46123      4   33   31
46124      1    8    8
46125      1   31   31
46126      7   14    4
46127      2   28   28
46128      1   13   13
46129      1   29   29
46130      1   11   11
46131      1    6    6
46132      1   21   21
46133      2   21   17
46134      1    1    1
46135      1   13   13
46136      4   17   11
46137      1   20   20
46138      1   17   17
46139      1   18   18
46140      1   19   19
46141      1   25   25
46142      5   28   10
46143      1   32   32
46144      1   29   29

[46145 rows x 3 columns]

In [136]:
def get_imask(S, V, data):
    i_mask = np.zeros((V,S,S))
    for wh in np.arange(V):
        f, l = data[wh, 0] , data[wh, 1]
        i_mask[wh, :f+1, l:] = 1
    return i_mask

In [180]:
tdata = np.array([[1,2], [5,12], [3, 13]])

In [138]:
tdata

array([[ 1,  2],
       [ 5, 12],
       [ 3, 13]])

In [139]:
t1 = get_imask(20, 3, tdata)

In [188]:
nz = np.zeros((3,20,20))
[nz[i, :j+1, k] for i,j,k in tdata]

ValueError: not enough values to unpack (expected 3, got 2)

In [193]:
[i for i in tdata]

[array([1, 2]), array([ 5, 12]), array([ 3, 13])]

In [110]:
r

array([[[0., 0., 1., ..., 1., 1., 1.],
        [0., 0., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 1., 1., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [142]:
r == t1

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  Tr

In [145]:
def get_imask2(S, V, data):
    s_mask = np.zeros([V,S])
    q_mask = np.zeros([V,S])
    for w in np.arange(V):
        f, l = data[w, 0] , data[w, 1]
        s_mask[w] = np.concatenate((np.ones(f+1), np.zeros(S - f -1)))
        q_mask[w] = np.concatenate((np.zeros(l), np.ones(S-l)))
    i_mask = np.einsum("is,iq->isq", s_mask, q_mask)
    return i_mask

In [203]:
def get_vmask(S):
    v_mask = np.zeros([S,S,S])
    for s in np.arange(S):
        for q in np.arange(s,S):
            c1 = np.zeros(s)
            c2 = np.ones(q-s)
            c3 = np.zeros(S-q)
            v_mask[s,q]= np.concatenate((c1, c2, c3))
    return v_mask
ocaz = get_vmask(3)

In [204]:
def get_BetaBi(a,b, S, Ni, Nn):
    # The beta binomial
    BBi  =  bound(betaln(Ni + a, Nn - Ni + b) - betaln(a, b),
                     Ni >= 0, Ni <= Nn,
                     a > 0, b > 0)
    # The above is the computation of the log, so we take the exponent
    return np.exp(BBi)

In [195]:
# For a given outcome in {1,S} (Frequency of capture that's not 0) 
# Generate the Binomial parameters n and i   choose(n, i)
# Nn is the duration from arrival to departure
# Ni is the Frequency we are intersted in
# Dim: SxSxS
def make_binmask(S):
    i = np.arange(S) + 1
    i = i[:, np.newaxis, np.newaxis] *  np.ones((S, S, S))
    n = np.broadcast_to(np.triu(np.ones([S,S]), 0).cumsum(axis =1), (S, S, S))
    return i, n
Ni, Nn = make_binmask(5)

In [206]:
get_BetaBi(1,1, 5, Ni, Nn).eval()

array([[[0.5       , 0.16666667, 0.08333333, 0.05      , 0.03333333],
        [0.        , 0.5       , 0.16666667, 0.08333333, 0.05      ],
        [0.        , 0.        , 0.5       , 0.16666667, 0.08333333],
        [0.        , 0.        , 0.        , 0.5       , 0.16666667],
        [0.        , 0.        , 0.        , 0.        , 0.5       ]],

       [[0.        , 0.33333333, 0.08333333, 0.03333333, 0.01666667],
        [0.        , 0.        , 0.33333333, 0.08333333, 0.03333333],
        [0.        , 0.        , 0.        , 0.33333333, 0.08333333],
        [0.        , 0.        , 0.        , 0.        , 0.33333333],
        [0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.25      , 0.05      , 0.01666667],
        [0.        , 0.        , 0.        , 0.25      , 0.05      ],
        [0.        , 0.        , 0.        , 0.        , 0.25      ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.     

In [207]:
Ni

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [208]:
def make_survival(S):
    mask = np.zeros([S,S,S])  # arrival, departure, presence_sequence
    for s in np.arange(S):
        for q in np.arange(s,S):
            c1 = np.zeros(s)
            c2 = np.ones(q-s)
            c3 = np.zeros(S-q)
            mask[s,q]= np.concatenate((c1, c2, c3))
    return mask
survival = make_survival(5)

In [209]:
survival

array([[[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 1., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [213]:
tt.triu(tt.ones((5,5)), 0).eval()

array([[1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [ ]:
tt